// Code generated by protoc-gen-go. DO NOT EDIT.
// source: communication.proto

package communication

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// The request message containing the user's name.
type UpdateFirebaseToken struct {
	KeyAccess            string   `protobuf:"bytes,1,opt,name=KeyAccess,proto3" json:"KeyAccess,omitempty"`
	FirebaseToken        string   `protobuf:"bytes,2,opt,name=FirebaseToken,proto3" json:"FirebaseToken,omitempty"`
	Phones               []string `protobuf:"bytes,3,rep,name=Phones,proto3" json:"Phones,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdateFirebaseToken) Reset()         { *m = UpdateFirebaseToken{} }
func (m *UpdateFirebaseToken) String() string { return proto.CompactTextString(m) }
func (*UpdateFirebaseToken) ProtoMessage()    {}
func (*UpdateFirebaseToken) Descriptor() ([]byte, []int) {
	return fileDescriptor_b64068f22c460ac1, []int{0}
}

func (m *UpdateFirebaseToken) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateFirebaseToken.Unmarshal(m, b)
}
func (m *UpdateFirebaseToken) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateFirebaseToken.Marshal(b, m, deterministic)
}
func (m *UpdateFirebaseToken) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateFirebaseToken.Merge(m, src)
}
func (m *UpdateFirebaseToken) XXX_Size() int {
	return xxx_messageInfo_UpdateFirebaseToken.Size(m)
}
func (m *UpdateFirebaseToken) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateFirebaseToken.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateFirebaseToken proto.InternalMessageInfo

func (m *UpdateFirebaseToken) GetKeyAccess() string {
	if m != nil {
		return m.KeyAccess
	}
	return ""
}

func (m *UpdateFirebaseToken) GetFirebaseToken() string {
	if m != nil {
		return m.FirebaseToken
	}
	return ""
}

func (m *UpdateFirebaseToken) GetPhones() []string {
	if m != nil {
		return m.Phones
	}
	return nil
}

// The response message containing the greetings
type ResultMessages struct {
	Success              bool     `protobuf:"varint,1,opt,name=Success,proto3" json:"Success,omitempty"`
	Error                string   `protobuf:"bytes,2,opt,name=Error,proto3" json:"Error,omitempty"`
	Message              string   `protobuf:"bytes,3,opt,name=Message,proto3" json:"Message,omitempty"`
	Result               string   `protobuf:"bytes,4,opt,name=Result,proto3" json:"Result,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ResultMessages) Reset()         { *m = ResultMessages{} }
func (m *ResultMessages) String() string { return proto.CompactTextString(m) }
func (*ResultMessages) ProtoMessage()    {}
func (*ResultMessages) Descriptor() ([]byte, []int) {
	return fileDescriptor_b64068f22c460ac1, []int{1}
}

func (m *ResultMessages) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ResultMessages.Unmarshal(m, b)
}
func (m *ResultMessages) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ResultMessages.Marshal(b, m, deterministic)
}
func (m *ResultMessages) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ResultMessages.Merge(m, src)
}
func (m *ResultMessages) XXX_Size() int {
	return xxx_messageInfo_ResultMessages.Size(m)
}
func (m *ResultMessages) XXX_DiscardUnknown() {
	xxx_messageInfo_ResultMessages.DiscardUnknown(m)
}

var xxx_messageInfo_ResultMessages proto.InternalMessageInfo

func (m *ResultMessages) GetSuccess() bool {
	if m != nil {
		return m.Success
	}
	return false
}

func (m *ResultMessages) GetError() string {
	if m != nil {
		return m.Error
	}
	return ""
}

func (m *ResultMessages) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func (m *ResultMessages) GetResult() string {
	if m != nil {
		return m.Result
	}
	return ""
}

type UserInfoRequest struct {
	PersonID             int32    `protobuf:"varint,1,opt,name=PersonID,proto3" json:"PersonID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UserInfoRequest) Reset()         { *m = UserInfoRequest{} }
func (m *UserInfoRequest) String() string { return proto.CompactTextString(m) }
func (*UserInfoRequest) ProtoMessage()    {}
func (*UserInfoRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_b64068f22c460ac1, []int{2}
}

func (m *UserInfoRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserInfoRequest.Unmarshal(m, b)
}
func (m *UserInfoRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserInfoRequest.Marshal(b, m, deterministic)
}
func (m *UserInfoRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserInfoRequest.Merge(m, src)
}
func (m *UserInfoRequest) XXX_Size() int {
	return xxx_messageInfo_UserInfoRequest.Size(m)
}
func (m *UserInfoRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UserInfoRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UserInfoRequest proto.InternalMessageInfo

func (m *UserInfoRequest) GetPersonID() int32 {
	if m != nil {
		return m.PersonID
	}
	return 0
}

type PurchaseCreditsRequest struct {
	PhoneNumber          string   `protobuf:"bytes,1,opt,name=PhoneNumber,proto3" json:"PhoneNumber,omitempty"`
	Value                int32    `protobuf:"varint,2,opt,name=Value,proto3" json:"Value,omitempty"`
	PlanSelect           string   `protobuf:"bytes,3,opt,name=PlanSelect,proto3" json:"PlanSelect,omitempty"`
	Date                 string   `protobuf:"bytes,4,opt,name=Date,proto3" json:"Date,omitempty"`
	ID                   string   `protobuf:"bytes,5,opt,name=ID,proto3" json:"ID,omitempty"`
	Description          string   `protobuf:"bytes,6,opt,name=Description,proto3" json:"Description,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PurchaseCreditsRequest) Reset()         { *m = PurchaseCreditsRequest{} }
func (m *PurchaseCreditsRequest) String() string { return proto.CompactTextString(m) }
func (*PurchaseCreditsRequest) ProtoMessage()    {}
func (*PurchaseCreditsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_b64068f22c460ac1, []int{3}
}

func (m *PurchaseCreditsRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PurchaseCreditsRequest.Unmarshal(m, b)
}
func (m *PurchaseCreditsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PurchaseCreditsRequest.Marshal(b, m, deterministic)
}
func (m *PurchaseCreditsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PurchaseCreditsRequest.Merge(m, src)
}
func (m *PurchaseCreditsRequest) XXX_Size() int {
	return xxx_messageInfo_PurchaseCreditsRequest.Size(m)
}
func (m *PurchaseCreditsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_PurchaseCreditsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_PurchaseCreditsRequest proto.InternalMessageInfo

func (m *PurchaseCreditsRequest) GetPhoneNumber() string {
	if m != nil {
		return m.PhoneNumber
	}
	return ""
}

func (m *PurchaseCreditsRequest) GetValue() int32 {
	if m != nil {
		return m.Value
	}
	return 0
}

func (m *PurchaseCreditsRequest) GetPlanSelect() string {
	if m != nil {
		return m.PlanSelect
	}
	return ""
}

func (m *PurchaseCreditsRequest) GetDate() string {
	if m != nil {
		return m.Date
	}
	return ""
}

func (m *PurchaseCreditsRequest) GetID() string {
	if m != nil {
		return m.ID
	}
	return ""
}

func (m *PurchaseCreditsRequest) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func init() {
	proto.RegisterType((*UpdateFirebaseToken)(nil), "communication.UpdateFirebaseToken")
	proto.RegisterType((*ResultMessages)(nil), "communication.ResultMessages")
	proto.RegisterType((*UserInfoRequest)(nil), "communication.UserInfoRequest")
	proto.RegisterType((*PurchaseCreditsRequest)(nil), "communication.PurchaseCreditsRequest")
}

func init() { proto.RegisterFile("communication.proto", fileDescriptor_b64068f22c460ac1) }

var fileDescriptor_b64068f22c460ac1 = []byte{
	// 463 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xac, 0x54, 0xc1, 0x4e, 0xdb, 0x40,
	0x10, 0x6d, 0x1c, 0x92, 0x92, 0x21, 0x01, 0x69, 0xa8, 0x90, 0x85, 0x5a, 0x14, 0x59, 0xad, 0xc4,
	0xa5, 0x39, 0xd0, 0x5b, 0x6f, 0x10, 0x53, 0x29, 0xaa, 0x40, 0x96, 0x53, 0xda, 0xf3, 0x66, 0x33,
	0xc0, 0xaa, 0xf6, 0xae, 0xd9, 0x5d, 0xb7, 0xa2, 0x1f, 0xd0, 0x43, 0x3f, 0xa8, 0xdf, 0x57, 0x79,
	0xbd, 0x29, 0xb1, 0x85, 0xc4, 0x81, 0xdc, 0xfc, 0x9e, 0x67, 0xde, 0x1b, 0xfb, 0x8d, 0x06, 0xf6,
	0xb9, 0xca, 0xf3, 0x52, 0x0a, 0xce, 0xac, 0x50, 0x72, 0x52, 0x68, 0x65, 0x15, 0x8e, 0x1a, 0x64,
	0x74, 0x07, 0xfb, 0x57, 0xc5, 0x92, 0x59, 0xfa, 0x24, 0x34, 0x2d, 0x98, 0xa1, 0x2f, 0xea, 0x3b,
	0x49, 0x7c, 0x0d, 0x83, 0xcf, 0x74, 0x7f, 0xca, 0x39, 0x19, 0x13, 0x76, 0xc6, 0x9d, 0xe3, 0x41,
	0xfa, 0x40, 0xe0, 0x5b, 0x18, 0x35, 0xca, 0xc3, 0xc0, 0x55, 0x34, 0x49, 0x3c, 0x80, 0x7e, 0x72,
	0xab, 0x24, 0x99, 0xb0, 0x3b, 0xee, 0x1e, 0x0f, 0x52, 0x8f, 0x22, 0x0d, 0xbb, 0x29, 0x99, 0x32,
	0xb3, 0x17, 0x64, 0x0c, 0xbb, 0x21, 0x83, 0x21, 0xbc, 0x9c, 0x97, 0x0f, 0x5e, 0xdb, 0xe9, 0x0a,
	0xe2, 0x2b, 0xe8, 0x9d, 0x6b, 0xad, 0xb4, 0x77, 0xa8, 0x41, 0x55, 0xef, 0x7b, 0xc3, 0xae, 0xe3,
	0x57, 0xb0, 0xf2, 0xac, 0xb5, 0xc3, 0x2d, 0xf7, 0xc2, 0xa3, 0xe8, 0x3d, 0xec, 0x5d, 0x19, 0xd2,
	0x33, 0x79, 0xad, 0x52, 0xba, 0x2b, 0xc9, 0x58, 0x3c, 0x84, 0xed, 0x84, 0xb4, 0x51, 0x72, 0x16,
	0x3b, 0xd7, 0x5e, 0xfa, 0x1f, 0x47, 0x7f, 0x3b, 0x70, 0x90, 0x94, 0x9a, 0xdf, 0x32, 0x43, 0x53,
	0x4d, 0x4b, 0x61, 0xcd, 0xaa, 0x6d, 0x0c, 0x3b, 0xee, 0x3b, 0x2e, 0xcb, 0x7c, 0x41, 0xda, 0xff,
	0x9b, 0x75, 0xaa, 0x9a, 0xf9, 0x2b, 0xcb, 0x4a, 0x72, 0x33, 0xf7, 0xd2, 0x1a, 0xe0, 0x11, 0x40,
	0x92, 0x31, 0x39, 0xa7, 0x8c, 0xb8, 0xf5, 0x63, 0xaf, 0x31, 0x88, 0xb0, 0x15, 0x33, 0x4b, 0x7e,
	0x6e, 0xf7, 0x8c, 0xbb, 0x10, 0xcc, 0xe2, 0xb0, 0xe7, 0x98, 0x60, 0x16, 0x57, 0xde, 0x31, 0x19,
	0xae, 0x45, 0x51, 0x65, 0x17, 0xf6, 0x6b, 0xef, 0x35, 0xea, 0xe4, 0x4f, 0xd0, 0x8a, 0x06, 0x13,
	0x18, 0xd4, 0x01, 0x9f, 0x16, 0x02, 0xa3, 0x49, 0x73, 0x25, 0x1e, 0x89, 0xfe, 0xf0, 0x4d, 0xab,
	0xa6, 0x99, 0x55, 0xf4, 0x02, 0x53, 0xd8, 0xf1, 0x8a, 0xcb, 0x5c, 0xc8, 0xcd, 0x68, 0xce, 0x61,
	0x58, 0xf7, 0x25, 0xec, 0xbe, 0x60, 0xd9, 0x46, 0x44, 0x4f, 0x7e, 0x07, 0x30, 0x3c, 0xcf, 0x99,
	0xc8, 0xe6, 0xa4, 0x7f, 0x08, 0x4e, 0x78, 0x01, 0xc3, 0xa9, 0x92, 0xd7, 0x42, 0xe7, 0x8e, 0xc6,
	0xa3, 0xb6, 0x4b, 0x73, 0x45, 0x9e, 0x70, 0xc0, 0x4b, 0x18, 0xa5, 0x64, 0xc8, 0x26, 0xcc, 0x98,
	0x9f, 0x4a, 0x2f, 0x9f, 0xab, 0xf7, 0x0d, 0xf6, 0x5a, 0x4b, 0x87, 0xef, 0x5a, 0x1d, 0x8f, 0x2f,
	0xe5, 0x13, 0xc2, 0x67, 0x1f, 0x21, 0x12, 0x6a, 0x72, 0xa3, 0x0b, 0x3e, 0x59, 0xe8, 0x5f, 0x2a,
	0xf7, 0x7c, 0xb3, 0xe9, 0x0c, 0xa7, 0xeb, 0x30, 0xa9, 0xae, 0x45, 0xd2, 0x59, 0xf4, 0xdd, 0xd9,
	0xf8, 0xf0, 0x2f, 0x00, 0x00, 0xff, 0xff, 0x95, 0x5a, 0xc5, 0x5c, 0x4d, 0x04, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// FirebaseTokenClient is the client API for FirebaseToken service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type FirebaseTokenClient interface {
	// Sends a greeting
	UpdateApi(ctx context.Context, in *UpdateFirebaseToken, opts ...grpc.CallOption) (*ResultMessages, error)
	UpdateAdmin(ctx context.Context, in *UpdateFirebaseToken, opts ...grpc.CallOption) (*ResultMessages, error)
	UpdatePaypal(ctx context.Context, in *UpdateFirebaseToken, opts ...grpc.CallOption) (*ResultMessages, error)
}

type firebaseTokenClient struct {
	cc *grpc.ClientConn
}

func NewFirebaseTokenClient(cc *grpc.ClientConn) FirebaseTokenClient {
	return &firebaseTokenClient{cc}
}

func (c *firebaseTokenClient) UpdateApi(ctx context.Context, in *UpdateFirebaseToken, opts ...grpc.CallOption) (*ResultMessages, error) {
	out := new(ResultMessages)
	err := c.cc.Invoke(ctx, "/communication.FirebaseToken/UpdateApi", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *firebaseTokenClient) UpdateAdmin(ctx context.Context, in *UpdateFirebaseToken, opts ...grpc.CallOption) (*ResultMessages, error) {
	out := new(ResultMessages)
	err := c.cc.Invoke(ctx, "/communication.FirebaseToken/UpdateAdmin", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *firebaseTokenClient) UpdatePaypal(ctx context.Context, in *UpdateFirebaseToken, opts ...grpc.CallOption) (*ResultMessages, error) {
	out := new(ResultMessages)
	err := c.cc.Invoke(ctx, "/communication.FirebaseToken/UpdatePaypal", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// FirebaseTokenServer is the server API for FirebaseToken service.
type FirebaseTokenServer interface {
	// Sends a greeting
	UpdateApi(context.Context, *UpdateFirebaseToken) (*ResultMessages, error)
	UpdateAdmin(context.Context, *UpdateFirebaseToken) (*ResultMessages, error)
	UpdatePaypal(context.Context, *UpdateFirebaseToken) (*ResultMessages, error)
}

// UnimplementedFirebaseTokenServer can be embedded to have forward compatible implementations.
type UnimplementedFirebaseTokenServer struct {
}

func (*UnimplementedFirebaseTokenServer) UpdateApi(ctx context.Context, req *UpdateFirebaseToken) (*ResultMessages, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateApi not implemented")
}
func (*UnimplementedFirebaseTokenServer) UpdateAdmin(ctx context.Context, req *UpdateFirebaseToken) (*ResultMessages, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateAdmin not implemented")
}
func (*UnimplementedFirebaseTokenServer) UpdatePaypal(ctx context.Context, req *UpdateFirebaseToken) (*ResultMessages, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdatePaypal not implemented")
}

func RegisterFirebaseTokenServer(s *grpc.Server, srv FirebaseTokenServer) {
	s.RegisterService(&_FirebaseToken_serviceDesc, srv)
}

func _FirebaseToken_UpdateApi_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateFirebaseToken)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FirebaseTokenServer).UpdateApi(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/communication.FirebaseToken/UpdateApi",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FirebaseTokenServer).UpdateApi(ctx, req.(*UpdateFirebaseToken))
	}
	return interceptor(ctx, in, info, handler)
}

func _FirebaseToken_UpdateAdmin_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateFirebaseToken)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FirebaseTokenServer).UpdateAdmin(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/communication.FirebaseToken/UpdateAdmin",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FirebaseTokenServer).UpdateAdmin(ctx, req.(*UpdateFirebaseToken))
	}
	return interceptor(ctx, in, info, handler)
}

func _FirebaseToken_UpdatePaypal_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateFirebaseToken)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FirebaseTokenServer).UpdatePaypal(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/communication.FirebaseToken/UpdatePaypal",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FirebaseTokenServer).UpdatePaypal(ctx, req.(*UpdateFirebaseToken))
	}
	return interceptor(ctx, in, info, handler)
}

var _FirebaseToken_serviceDesc = grpc.ServiceDesc{
	ServiceName: "communication.FirebaseToken",
	HandlerType: (*FirebaseTokenServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "UpdateApi",
			Handler:    _FirebaseToken_UpdateApi_Handler,
		},
		{
			MethodName: "UpdateAdmin",
			Handler:    _FirebaseToken_UpdateAdmin_Handler,
		},
		{
			MethodName: "UpdatePaypal",
			Handler:    _FirebaseToken_UpdatePaypal_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "communication.proto",
}

// EmailServiceClient is the client API for EmailService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type EmailServiceClient interface {
	ConfirmEmail(ctx context.Context, in *UserInfoRequest, opts ...grpc.CallOption) (*ResultMessages, error)
	ResetPassword(ctx context.Context, in *UserInfoRequest, opts ...grpc.CallOption) (*ResultMessages, error)
	PurchaseCredits(ctx context.Context, in *PurchaseCreditsRequest, opts ...grpc.CallOption) (*ResultMessages, error)
}

type emailServiceClient struct {
	cc *grpc.ClientConn
}

func NewEmailServiceClient(cc *grpc.ClientConn) EmailServiceClient {
	return &emailServiceClient{cc}
}

func (c *emailServiceClient) ConfirmEmail(ctx context.Context, in *UserInfoRequest, opts ...grpc.CallOption) (*ResultMessages, error) {
	out := new(ResultMessages)
	err := c.cc.Invoke(ctx, "/communication.EmailService/ConfirmEmail", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *emailServiceClient) ResetPassword(ctx context.Context, in *UserInfoRequest, opts ...grpc.CallOption) (*ResultMessages, error) {
	out := new(ResultMessages)
	err := c.cc.Invoke(ctx, "/communication.EmailService/ResetPassword", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *emailServiceClient) PurchaseCredits(ctx context.Context, in *PurchaseCreditsRequest, opts ...grpc.CallOption) (*ResultMessages, error) {
	out := new(ResultMessages)
	err := c.cc.Invoke(ctx, "/communication.EmailService/PurchaseCredits", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// EmailServiceServer is the server API for EmailService service.
type EmailServiceServer interface {
	ConfirmEmail(context.Context, *UserInfoRequest) (*ResultMessages, error)
	ResetPassword(context.Context, *UserInfoRequest) (*ResultMessages, error)
	PurchaseCredits(context.Context, *PurchaseCreditsRequest) (*ResultMessages, error)
}

// UnimplementedEmailServiceServer can be embedded to have forward compatible implementations.
type UnimplementedEmailServiceServer struct {
}

func (*UnimplementedEmailServiceServer) ConfirmEmail(ctx context.Context, req *UserInfoRequest) (*ResultMessages, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ConfirmEmail not implemented")
}
func (*UnimplementedEmailServiceServer) ResetPassword(ctx context.Context, req *UserInfoRequest) (*ResultMessages, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ResetPassword not implemented")
}
func (*UnimplementedEmailServiceServer) PurchaseCredits(ctx context.Context, req *PurchaseCreditsRequest) (*ResultMessages, error) {
	return nil, status.Errorf(codes.Unimplemented, "method PurchaseCredits not implemented")
}

func RegisterEmailServiceServer(s *grpc.Server, srv EmailServiceServer) {
	s.RegisterService(&_EmailService_serviceDesc, srv)
}

func _EmailService_ConfirmEmail_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UserInfoRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EmailServiceServer).ConfirmEmail(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/communication.EmailService/ConfirmEmail",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EmailServiceServer).ConfirmEmail(ctx, req.(*UserInfoRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _EmailService_ResetPassword_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UserInfoRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EmailServiceServer).ResetPassword(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/communication.EmailService/ResetPassword",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EmailServiceServer).ResetPassword(ctx, req.(*UserInfoRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _EmailService_PurchaseCredits_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PurchaseCreditsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EmailServiceServer).PurchaseCredits(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/communication.EmailService/PurchaseCredits",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EmailServiceServer).PurchaseCredits(ctx, req.(*PurchaseCreditsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _EmailService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "communication.EmailService",
	HandlerType: (*EmailServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ConfirmEmail",
			Handler:    _EmailService_ConfirmEmail_Handler,
		},
		{
			MethodName: "ResetPassword",
			Handler:    _EmailService_ResetPassword_Handler,
		},
		{
			MethodName: "PurchaseCredits",
			Handler:    _EmailService_PurchaseCredits_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "communication.proto",
}
